### ISSUE TITLE
Document how to use Flask decorator with AppFactory/Blueprint pattern

### ISSUE THREAD

**Issue by pamelafox** [rayluo/identity#24]
I had to do this in my create_app function-

    with app.app_context():
        app.auth = Auth(
            app,
            authority=os.getenv("AUTHORITY"),
            client_id=os.getenv("CLIENT_ID"),
            client_credential=os.getenv("CLIENT_SECRET"),
            redirect_uri=os.getenv("REDIRECT_URI"),
        )

And then make a wrapper decorator in my Blueprint:
  
    def login_required(f):
        """Decorator to require login for a route."""
        @wraps(f)
        def decorated_function(*args, **kwargs):
            return current_app.auth.login_required(f)(*args, **kwargs)
        return decorated_function

**Comment by rayluo** [comment]
Would you mind share me with more code snippets of your project? I want to better understand how it uses the app object and the wrapper decorator. You may reach me offline if your app is not publicly available.

<sub>

Note to self: [Demystifying Flask’s “Application Factory”](https://hackersandslackers.com/flask-application-factory/)

</sub>

**Comment by pamelafox** [comment]
@rayluo Here's a full project with similar pattern, though I made a few tweaks:
https://github.com/Azure-Samples/openai-chat-app-entra-auth-local/blob/main/src/quartapp/

Here's where I construct Auth, in the before_serving function:
https://github.com/Azure-Samples/openai-chat-app-entra-auth-local/blob/main/src/quartapp/chat.py#L84

Here's my decorator wrapper:
https://github.com/Azure-Samples/openai-chat-app-entra-auth-local/blob/main/src/quartapp/chat.py#L120

That wrapper ensures I don't call bp.auth before it exists.

Maybe the documentation could just link to examples? I could send a PR with links.

**Comment by cheizer** [comment]
Hello, I see this as closed but was #31 actually tested? 

I'm playing around with this in a test app and not having any luck.

I keep getting a error "NameError: name 'auth' is not defined"

--main
**__init__.py**
from flask import Blueprint
from myapp.auth import auth

main = Blueprint('main', __name__)

from . import views

**views.py**
from flask import render_template, current_app

from . import main

@main.route('/')
@auth.login_required
def index(context):
    return render_template('index.html', config=current_app.config, keys=current_app.config.keys())

**Comment by rayluo** [comment]
> Hello, I see this as closed but was [#31](https://github.com/rayluo/identity/pull/31) actually tested?

I suppose the answer would be a [yes](https://github.com/rayluo/identity/pull/31#issuecomment-2163125053)?

It is hard to tell whether your code snippet above [properly defined the `auth` like this](https://github.com/rayluo/identity/pull/31/files#diff-0e5724d69e294bdf22bc90815598238ec8cc904b2619d85491ea78c604c99ea3R29-R57).

**Comment by cheizer** [comment]
Thank you. I do really like the module. I finally got it working. 

1) I had a namespace issue. 
2) Because of the way you implemented blueprints support I was unable to use the flask app instance with all of the config data to init the Auth module. 
Flask extensions are designed to be instantiated without an app instance. Outside the factory, define your extensions. Inside the factory, call init_app to associate the app with the extension.

Quick Example ..
-- app.py
```

auth = Auth()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config_object)
    auth.init_app(app, authority=..., client_id=..., ...)
    
    app.register_blueprint(my_blueprint)

    return app
```

**Comment by rayluo** [comment]
> I finally got it working.
> 
> 1. ...
> 2. Because of the way you implemented blueprints support I was unable to use the flask app instance with all of the config data to init the Auth module.
>    Flask extensions are designed to be instantiated without an app instance. Outside the factory, define your extensions. Inside the factory, call init_app to associate the app with the extension.
> 
> Quick Example .. -- app.py
> 
> ```
> 
> auth = Auth()
> 
> def create_app():
>     app = Flask(__name__)
>     app.config.from_object(config_object)
>     auth.init_app(app, authority=..., client_id=..., ...)
>     
>     app.register_blueprint(my_blueprint)
> 
>     return app
> ```

["Generally ..."](https://flask.palletsprojects.com/en/stable/extensions/#using-extensions), you are right. But Identity library is not a general Flask extension. It is designed to support multiple different Python web frameworks ([currently 3](https://github.com/rayluo/identity?tab=readme-ov-file#installation)), with consistent configuration (so that official [sample](https://github.com/Azure-Samples/ms-identity-python-webapp?tab=readme-ov-file#how-to-configure-and-use-this-sample)s of those 3 web frameworks can even share the same `.env` template) thus reducing my support workload).

Regardless, I don't see real differences between `auth = Auth(..., client_id=..., ...); auth.init_app(app)` and `auth = Auth(); auth.init_app(app, client_id=..., ...)`.

If you want to elaborate a case that the current API falls short, or a better idea, please create a new github issue.
